package com.Wsdl2Code.WebServices.pqrdService;

//------------------------------------------------------------------------------
// <wsdl2code-generated>
//    This code was generated by http://www.wsdl2code.com version  2.5
//
// Date Of Creation: 10/3/2013 4:21:41 AM
//    Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code  Version
//
import org.ksoap2.serialization.KvmSerializable;
import org.ksoap2.serialization.PropertyInfo;
import java.util.Hashtable;
import org.ksoap2.serialization.SoapObject;
import org.ksoap2.serialization.SoapPrimitive;

public class respuestaRegistroVO implements KvmSerializable {
    
    public int anno;
    public boolean annoSpecified;
    public String mensajeError;
    public long numRadicado;
    public boolean numRadicadoSpecified;
    
    public respuestaRegistroVO(){}
    
    public respuestaRegistroVO(SoapObject soapObject)
    {
        if (soapObject == null)
            return;
        if (soapObject.hasProperty("anno"))
        {
            Object obj = soapObject.getProperty("anno");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                anno = Integer.parseInt(j.toString());
            }else if (obj!= null && obj instanceof Number){
                anno = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("annoSpecified"))
        {
            Object obj = soapObject.getProperty("annoSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                annoSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                annoSpecified = (Boolean) obj;
            }
        }
        if (soapObject.hasProperty("mensajeError"))
        {
            Object obj = soapObject.getProperty("mensajeError");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                mensajeError = j.toString();
            }else if (obj!= null && obj instanceof String){
                mensajeError = (String) obj;
            }
        }
        if (soapObject.hasProperty("numRadicado"))
        {
            Object obj = soapObject.getProperty("numRadicado");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                numRadicado = Long.parseLong(j.toString());
            }else if (obj!= null && obj instanceof Number){
                numRadicado = (Integer) obj;
            }
        }
        if (soapObject.hasProperty("numRadicadoSpecified"))
        {
            Object obj = soapObject.getProperty("numRadicadoSpecified");
            if (obj != null && obj.getClass().equals(SoapPrimitive.class)){
                SoapPrimitive j =(SoapPrimitive) obj;
                numRadicadoSpecified = Boolean.parseBoolean(j.toString());
            }else if (obj!= null && obj instanceof Boolean){
                numRadicadoSpecified = (Boolean) obj;
            }
        }
    }
    @Override
    public Object getProperty(int arg0) {
        switch(arg0){
            case 0:
                return anno;
            case 1:
                return annoSpecified;
            case 2:
                return mensajeError;
            case 3:
                return numRadicado;
            case 4:
                return numRadicadoSpecified;
        }
        return null;
    }
    
    @Override
    public int getPropertyCount() {
        return 5;
    }
    
    @Override
    public void getPropertyInfo(int index, @SuppressWarnings("rawtypes") Hashtable arg1, PropertyInfo info) {
        switch(index){
            case 0:
                info.type = PropertyInfo.INTEGER_CLASS;
                info.name = "anno";
                break;
            case 1:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "annoSpecified";
                break;
            case 2:
                info.type = PropertyInfo.STRING_CLASS;
                info.name = "mensajeError";
                break;
            case 3:
                info.type = Long.class;
                info.name = "numRadicado";
                break;
            case 4:
                info.type = PropertyInfo.BOOLEAN_CLASS;
                info.name = "numRadicadoSpecified";
                break;
        }
    }
    
    @Override
    public void setProperty(int arg0, Object arg1) {
    }
    
}
